name: meezy_starter
description: A production-ready template for Flutter applications.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

workspace:
  - packages/meezy_core
  - packages/meezy_ui