name: meezy_starter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any

  # Localization
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Networking
  dio: 5.3.3
  dart_jsonwebtoken: ^2.13.0

  # Persisting
  shared_preferences: 2.2.2

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: 7.11.0
  logging: 1.2.0

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path: 1.8.3
  path_provider: 2.1.0
  flutter_native_splash: 2.3.5
  provider: ^6.1.2

  # Packages
  auto_route: ^7.6.0
  flutter_smart_dialog: ^4.9.5+1

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^7.2.0

  # Lints
  sizzle_lints: 2.0.2

  # Utils
  flutter_gen_runner: 5.3.2
  flutter_launcher_icons: 0.13.1
  freezed: ^2.4.7
  melos: 3.2.0
  intl_utils: 2.8.5

flutter:
  uses-material-design: true

  generate: false

  assets:
    # Add assets from the images directory to the application.
    - assets/images/


