name: meezy_ui
description: "Meezy UI is a customizable Flutter UI package designed to provide reusable components, themes, and styling utilities for the Meezy Starter framework. It includes pre-built widgets, responsive layouts, and design system elements to streamline the development of visually consistent and high-performance Flutter applications. With support for dark mode, adaptive themes, and animation utilities, Meezy UI helps developers build beautiful and scalable user interfaces efficiently."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

# Use shared dependency resolution
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  hovering: ^1.0.4
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  flutter_smart_dialog: ^4.9.8+6
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1
  blur: ^4.0.0
  lottie: ^3.3.1
  rive: ^0.12.2
  flutter_shaders: ^0.1.3
  flutter_elastic_list_view: ^0.0.5+2
  soft_edge_blur: ^0.1.3
  auto_route:
  flutter_svg:
  auto_size_text: ^3.0.0
  super_tooltip: ^2.0.9
  motion: ^2.0.1
  flutter_blurhash: ^0.8.2
  astro_refresh_indicator: ^1.0.4
  pull_to_refresh: ^2.0.0
  vibration: ^3.1.3
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  shaders:
    - lib/src/shaders/glsl/water_color_blending.frag
    - lib/src/shaders/glsl/shockwave.frag
    - lib/src/shaders/glsl/progressive_blur.frag

  assets:
    - assets/arrows/