name: meezy_core
description: "A new Flutter project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

# Use shared dependency resolution
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Logging
  stack_trace: 1.12.1
  sentry_flutter: 8.14.0
  logging: 1.2.0

  path: 1.9.1
  analyzer: ^7.3.0
  collection: any
  async: any
  image_picker: 1.1.2
  camera:
  meta: ^1.15.0
  flutter_svg: 2.0.10+1
  pinput: 4.0.0
  curl_logger_dio_interceptor: 1.0.0
  pretty_dio_logger: 1.3.1
  auto_route: ^10.0.1
  firebase_crashlytics: ^4.3.4
  supabase_flutter: ^2.8.4
  characters: ^1.4.0
  blurhash_ffi: ^1.2.7

  # Localization
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Networking
  dio: 5.3.3
  dart_jsonwebtoken: ^2.13.0

  # Persisting
  shared_preferences: 2.2.2

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path_provider: ^2.1.4
  flutter_native_splash: 2.3.5
  provider: 6.1.2
  hovering: 1.0.4
  flutter_keyboard_visibility: 6.0.0
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  quiver: 3.2.2
  flutter_udid: 4.0.0
  firebase_analytics: 11.4.4
  permission_handler: 11.4.0
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0
  freezed: 2.5.8
  auto_route_generator: ^10.0.1
