name: meezy_core
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

# Use shared dependency resolution
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: 7.11.0
  logging: 1.2.0

  path: ^1.9.0
  analyzer: ^6.4.1
  collection: any
  async: any
  meta: ^1.11.0
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  curl_logger_dio_interceptor: ^1.0.0
  flutter_login: ^5.0.0
  pretty_dio_logger: ^1.3.1

  # Localization
  intl: 0.20.2
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: 2.1.0
  rxdart: 0.27.7

  # BLoC
  flutter_bloc: 8.1.3

  # Networking
  dio: 5.3.3
  dart_jsonwebtoken: ^2.13.0

  # Persisting
  shared_preferences: 2.2.2

  # Utils
  pure: 0.2.0
  platform_info: 4.0.2
  bloc_concurrency: 0.2.2
  path_provider: 2.1.0
  flutter_native_splash: 2.3.5
  provider: ^6.1.2
  flutter_web_auth_2: ^3.1.1
  lottie: ^3.1.0
  hovering: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
